import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function GET() {
  try {
    // Path to the deployment summary generated by the contracts wizard
    const summaryPath = path.join(
      process.cwd(),
      '..',
      'contracts',
      'input',
      'evvmDeploymentSummary.json'
    );

    // Check if file exists
    if (!fs.existsSync(summaryPath)) {
      return NextResponse.json(
        {
          error: 'No EVVM deployments found',
          message:
            'Please deploy an EVVM instance first by running: cd contracts && npm run wizard',
        },
        { status: 404 }
      );
    }

    // Read and parse the file
    const fileContent = fs.readFileSync(summaryPath, 'utf-8');
    const deployment = JSON.parse(fileContent);

    // Return as array for consistency
    return NextResponse.json([deployment]);
  } catch (error: any) {
    console.error('Error reading deployment summary:', error);
    return NextResponse.json(
      {
        error: 'Failed to load deployment data',
        message: error.message,
      },
      { status: 500 }
    );
  }
}
