'use client';

import { useEffect, useState } from 'react';

export interface EvvmDeployment {
  chainId: number;
  networkName: string;
  evvm: string;
  nameService: string;
  staking: string;
  estimator: string;
  treasury: string;
  p2pSwap: string;
  evvmID: number;
  evvmName: string;
  registry: string;
  admin: string;
  goldenFisher: string;
  activator: string;
}

/**
 * Hook to load EVVM deployment information
 * Automatically reads from the deployment summary generated by the wizard
 */
export function useEvvmDeployment() {
  const [deployment, setDeployment] = useState<EvvmDeployment | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadDeployment() {
      try {
        setLoading(true);
        const response = await fetch('/api/deployments', {
          // Disable caching to always get fresh data
          cache: 'no-store',
          headers: {
            'Cache-Control': 'no-cache',
          },
        });

        if (!response.ok) {
          throw new Error(`Failed to load deployment: ${response.statusText}`);
        }

        const data = await response.json();
        // API returns array, get first element
        const deploymentData = Array.isArray(data) ? data[0] : data;
        setDeployment(deploymentData);
        setError(null);
      } catch (err: any) {
        console.error('Error loading deployment:', err);
        setError(err.message || 'Failed to load deployment');
        setDeployment(null);
      } finally {
        setLoading(false);
      }
    }

    loadDeployment();
  }, []);

  return { deployment, loading, error };
}
